# Generated by Django 3.2.16 on 2022-12-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('mobile', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
                ('dob', models.DateTimeField()),
                ('address', models.TextField(max_length=255)),
                ('age', models.IntegerField(default=1)),
            ],
        ),
    ]
