# Generated by Django 3.2.16 on 2023-02-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='father_name',
            field=models.CharField(default='Father', max_length=255),
        ),
    ]
